# [Choice] Debian version (use bullseye on local arm64/Apple Silicon): bookworm, bullseye, buster
#ARG VARIANT="bookworm-20250317"
FROM mcr.microsoft.com/devcontainers/base:debian-12

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
